# Generated by Django 4.0.2 on 2022-02-25 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spectorapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='age',
            field=models.IntegerField(default=18),
        ),
    ]
