# Generated by Django 4.0.2 on 2022-02-26 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spectorapp', '0002_userdata_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sports',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=200)),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spectorapp.sports')),
            ],
        ),
    ]
