# Generated by Django 4.0.2 on 2022-03-09 19:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spectorapp', '0003_sports_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='dateTime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
