# Generated by Django 4.0.2 on 2022-03-09 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spectorapp', '0004_activity_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='dateTime',
            field=models.DateTimeField(default='09.03.2022 20:00:54'),
        ),
    ]
