# Generated by Django 4.0.2 on 2022-03-09 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spectorapp', '0004_activity_maxmembers_activity_members'),
        ('spectorapp', '0006_alter_profile_owner'),
    ]

    operations = [
    ]
