# Generated by Django 4.0.2 on 2022-03-09 20:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('spectorapp', '0006_alter_activity_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='dateTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 9, 20, 5, 11, 13431, tzinfo=utc)),
        ),
    ]
