# Generated by Django 4.0.2 on 2022-03-10 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spectorapp', '0007_merge_20220309_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='bruh',
            field=models.CharField(default='hi', max_length=2),
        ),
    ]
