# Generated by Django 4.0.2 on 2022-03-09 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spectorapp', '0007_alter_activity_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='dateTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
