# Generated by Django 4.0.2 on 2022-03-09 20:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('spectorapp', '0008_alter_activity_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='dateTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
