# Generated by Django 4.0.2 on 2022-03-11 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spectorapp', '0009_activity_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='bruh',
        ),
    ]
