# Generated by Django 4.0.2 on 2022-03-11 18:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('spectorapp', '0010_remove_activity_bruh'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='dateTime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date & Time'),
        ),
    ]
