# Generated by Django 4.0.2 on 2022-03-30 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spectorapp', '0013_remove_profile_id_alter_activity_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(default='Bio', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(default='Full Name', max_length=30),
        ),
    ]
